apiVersion: v1
kind: Service
metadata:
  name: dadp
  labels:
    service: dadp
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    #nodePort: 32000
  selector:
    service: dadp
  #type: NodePort
  type: ClusterIP